version: '3.8'

services:
  frontend:
    build: ./ml-kurkkumopo-frontend/.
    ports:
      - 3000:3000
    container_name: frontend

  backend:
    build: ./ml-kurkkumopo-backend/.
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    container_name: backend
    depends_on:
      - training

  training:
    build: ./ml-kurkkumopo-training/.
    volumes:
      - model:/src/model
      - images:/src/imgs
      - data:/src/data
    container_name: training

volumes:
  model:
  images:
  data:
